### ISSUE TITLE
想把wizard移至”系统“菜单，该如何修改？

### ISSUE THREAD

**Issue by 5points** [sirpdboy/luci-app-netwizard#6]
因为默认直接编译后，主题没有支持此插件的原因。导致菜单显示不太美观。
于是修改了“wizard.lua”文件的第10行，分别改了两次，但编译出来均无效果。
```
第一次：
page = entry({"admin", "system", "wizard"}, cbi("system/wizard"), _("Inital Setup"), 21)
第二次：
page = entry({"admin", "system", "wizard"}, cbi("wizard/wizard"), _("Inital Setup"), 21)
```
进入路由界面就会显示这个错误
```
No page is registered at '/admin/wizard'.
If this url belongs to an extension, make sure it is properly installed.
If the extension was recently installed, try removing the /tmp/luci-indexcache file.
```
请问，我还需要修改什么才能达到效果？

**Comment by XuHuapeng001** [comment]
modules/luci-base/luasrc/dispatcher.lua   line 114: 
	local default_path_info = fs.access("/etc/config/wizard") and (not fs.access("/etc/config/finished")) and "admin/wizard" or ""

change "admin/wizard" to “admin/system/wizard"

**Comment by sirpdboy** [comment]
新版本已经移动到系统菜单了
